name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ephemeral-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Display message
        run: echo "Runner is operational!"
