param (
    [string]$controllerStatus,
    [string]$phaseStatus,
    [string]$compStatusPhase1,
    [string]$compStatusPhase2,
    [string]$compStatusPhase3
)

# Set controllerStatus as output
Add-Content -Path $env:GITHUB_OUTPUT -Value "controller-status=$controllerStatus"

# Process Controller Jobs Dynamically
$controllerMatches = [regex]::Matches($controllerStatus, "(\S+) status: (.*?)(,|$)")
foreach ($match in $controllerMatches) {
    $component = $match.Groups[1].Value
    $status = $match.Groups[2].Value
    Add-Content -Path $env:GITHUB_OUTPUT -Value "$component-status=$component status: $status"
}

# Set phaseStatus as output
Add-Content -Path $env:GITHUB_OUTPUT -Value "overall-phase-status=$phaseStatus"

# Process Phase Status Dynamically
$phaseMatches = [regex]::Matches($phaseStatus, "(\S+) status: (.*?)(,|$)")
$phaseJobMapping = @{}
foreach ($match in $phaseMatches) {
    $phase = $match.Groups[1].Value
    $status = $match.Groups[2].Value
    Add-Content -Path $env:GITHUB_OUTPUT -Value "${phase}_status=$phase status: $status"
    $phaseJobMapping[$phase] = ""
}

# Assign respective component statuses dynamically
$compStatuses = @($compStatusPhase1, $compStatusPhase2, $compStatusPhase3)
$index = 0
foreach ($phase in $phaseJobMapping.Keys) {
    if ($index -lt $compStatuses.Count) {
        $phaseJobMapping[$phase] = $compStatuses[$index]
        $index++
    }
}

# Process Component Status for Each Phase Dynamically
foreach ($phase in $phaseJobMapping.Keys) {
    $compStatus = $phaseJobMapping[$phase]
    Add-Content -Path $env:GITHUB_OUTPUT -Value "${phase}-status=$compStatus"

    if (-not $compStatus) {
        Add-Content -Path $env:GITHUB_OUTPUT -Value "${phase}-job1-status=create-component-matrix status: skipped"
        Add-Content -Path $env:GITHUB_OUTPUT -Value "${phase}-job2-status=deploy-to-AzService status: skipped"
    } else {
        # Extract job statuses dynamically
        $jobMatches = [regex]::Matches($compStatus, "(\S+) status: (.*?)(,|$)")
        foreach ($jobMatch in $jobMatches) {
            $jobName = $jobMatch.Groups[1].Value
            $jobStatus = $jobMatch.Groups[2].Value
            Add-Content -Path $env:GITHUB_OUTPUT -Value "${phase}-${jobName}-status=$jobName status: $jobStatus"
        }
    }
}
