name: AV-Fullstack 

on:
  workflow_dispatch:

permissions:
   contents: read
   id-token: write

jobs:
  CI-workflow-dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: CI-mvc
        run: echo "Event Trigger Workflow Dispatch"
    
  CI-dispatch-mvc:
    needs: [CI-workflow-dispatch]
    uses: ./.github/workflows/AV-mvc.yml
    secrets: inherit

  CI-dispatch-backend:
    needs: [CI-workflow-dispatch]
    uses: ./.github/workflows/AV-backend.yml
    secrets: inherit

  CI-dispatch-sphereengine:
    needs: [CI-workflow-dispatch]
    uses: ./.github/workflows/AV-sphereengine.yml
    secrets: inherit
