name: AV-mvc

on:
  #pull_request:
    #paths:
      #- 'mvc/**'
  workflow_call:
  push:
    paths:
      - ".github/workflows/AV-mvc.yml"
      - "mvc/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Bump version
        id: bump
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        uses: ./.github/actions/semversion-calculation
        with:
          component: "mvc"

      - name: Push artifact to Artifactory (placeholder)
        run: |
          echo "Pushing artifact to Artifactory..." 
