name: AV-SphereEngine

on:
  workflow_call:
  push:
    paths:
      - ".github/workflows/AV-sphereengine.yml"
      - "sphereengine/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload to artifact 
        run: |
           echo "Submitting solution to Sphere Engine API..."
