name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
     
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-app
          path: target
  deploy:
      needs: build
      runs-on: windows-latest
      steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: web-app
          path: /tmp
          
      - name: List Contents of /tmp  # Added for debugging
        run: ls -l /tmp
      - name: Set Permissions
        run: icacls "C:\Program Files\Apache Software Foundation\Tomcat 10.1\webapps" /grant Everyone:(OI)(CI)F
      - name: Deploy to Tomcat
        run: cp /tmp/*.war "/C:/Program Files/Apache Software Foundation/Tomcat 10.1/webapps/"
