name: CI
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Listing the target directory
        run : ls -R 
        working-directory: /home/runner/work/TicketReservation/TicketReservation/target
      - name: Create staging directory and copy .war
        run: |
          mkdir staging
          cp target/*.war staging/
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-app
          path: staging
      - name: Listing the Staging directory
        run : ls -R 
        working-directory: /home/runner/work/TicketReservation/TicketReservation/staging
      - name: Create an issue
        uses: JasonEtco/create-an-issue@v2.9.2
        env :  
          GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN }}
	        ENVIRONMENT: Dev
	        RUNNUMBER: ${{ github.run_number }}
        with:  
          filename: .github/deployment-approval.md
