name: Java CI with Maven

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Listing the target directory
        run : ls -R 
        working-directory: /home/runner/work/TicketReservation/TicketReservation/target
      - name: Create staging directory and copy .war
        run: |
          mkdir staging
          cp target/*.war staging/
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-app
          path: staging
      - name: Listing the Staging directory
        run : ls -R 
        working-directory: /home/runner/work/TicketReservation/TicketReservation/staging
  approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: santhosh-158
          minimum-approvals: 1
          issue-title: "Deploying the java web app to Tomcat"
          issue-body: "Please approve or deny the deployment"
          exclude-workflow-initiator-as-approver: false
          timeout-minutes: 30  # Set a 30-minute time limit for the approval process
  deploy:
    needs: approval
    runs-on: self-hosted
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: web-app 
        path: D:/github/
    - name: Deploy to Tomcat
      run: cp D:/github/*.war "C:/Program Files/Apache Software Foundation/Tomcat 10.1/webapps/"
