name: Main Build Workflow
on:
  workflow_dispatch

jobs:
  Call-workflow-for-build:
    runs-on: ubuntu-latest
    steps:
      - name: Call Reusable Build Workflow
        uses: ./.github/workflows/reusable-workflow.yml
  Call-workflow-for-deploy:
    runs-on: ubuntu-latest
    needs: Call-workflow-for-build 
    steps:
      - name: Call Deploy Workflow
        uses: ./.github/workflows/deploy-workflow.yml
