name: Caller-workflow
on:
  workflow_dispatch:
   inputs:
      deploy_target:
        description: 'Specify the deployment environment (Call-Dev or call-prod or call-prod1)?'
        required: true
        type: string
        

jobs:
  Call-workflow-for-build:
    uses: ./.github/workflows/Build-workflow.yml
    

  Call-workflow-for-deploy:
    
    needs: Call-workflow-for-build
    uses: ./.github/workflows/Deploy-workflow.yml
    with:
          environment: ${{ github.event.inputs.environment }}
    
    
 
  
