name: Caller-workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev and Prod)?'
        required: true
        type: environment
        
jobs:
  Call-workflow-for-deploy:
    uses: ./.github/workflows/Deploy-workflow.yml   
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit
    id: deploy

  Handle-deploy-result:
    needs: Call-workflow-for-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check the output of deploy workflow
        run: |
          echo "Deploy Workflow Status: ${{ needs.Call-workflow-for-deploy.outputs.deploy_status }}"
          if [[ "${{ needs.Call-workflow-for-deploy.outputs.deploy_status }}" != "success" ]]; then
            echo "Deployment failed, exiting..."
            exit 1
          fi
