name: Caller-workflow
on:
  workflow_dispatch:
   inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        

jobs:
  Call-workflow-for-build:
     runs-on: ubuntu-latest
     steps:
      - name: Call Build Workflow
        uses: ./.github/workflows/Build-workflow.yml  
    

  Call-workflow-for-deploy:
    runs-on: self-hosted
    steps:
      - name: Call Deploy Workflow
        uses: ./.github/workflows/Deploy-workflow.yml
        with:
          environment: ${{ github.event.inputs.environment }}
   
    
 
  
