name: Caller-workflow
on:
  workflow_dispatch:
   inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        

jobs:
  
    

  Call-workflow-for-deploy:
    
    uses: ./.github/workflows/Deploy-workflow.yml
    with:
          environment: ${{ github.event.inputs.environment }}
   
    
 
  
