name: Caller-workflow
on:
  workflow_dispatch

jobs:
  Call-workflow-for-build:
    uses: ./.github/workflows/Build-workflow.yml
    
  Call-workflow-for-Dev-deploy:
    needs: [Call-workflow-for-build]
    uses: ./.github/workflows/Deploy-workflow.yml 
	
  Call-workflow-for-Prod-deploy:
    needs: Call-workflow-for-Dev-deploy
    uses: ./.github/workflows/Deploy-workflow.yml 

