name: Caller-workflow
on:
  workflow_dispatch

jobs:
  Call-workflow-for-build:
    uses: ./.github/workflows/Build-workflow.yml
    with:
          releaseType: ${{ github.event.inputs.releaseType }}
  Call-workflow-for-deploy:
    needs: Call-workflow-for-build
    uses: ./.github/workflows/Deploy-workflow.yml 
    with:
          releaseType: ${{ github.event.inputs.releaseType }}

 
