name: Caller-workflow
on:
  workflow_dispatch:
   
jobs:
  Call-workflow-for-build:
    uses: ./.github/workflows/Build-workflow.yml
    
  Call-Deploy-Dev:
    runs-on: self-hosted
    if: ${{ github.event.inputs.releaseType == 'Dev' }}
    needs: [Call-workflow-for-build]
    steps:
      - name: Call Deploy-Dev Workflow
        uses: ./.github/workflows/Deploy-workflow.yml
        with:
          releaseType: ${{ github.event.inputs.releaseType }}

  Call-Deploy-Prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.releaseType == 'Prod' }}
    steps:
      - name: Call Deploy-Prod Workflow
        uses: ./.github/workflows/Deploy-workflow.yml
        with:
          releaseType: ${{ github.event.inputs.releaseType }}
