name: Caller-workflow
on:
  workflow_dispatch

jobs:
  Call-build-workflow:
    uses: ./.github/workflows/Build-workflow.yml
    
  Call-Dev-deploy-workflow:
    
    uses: ./.github/workflows/Deploy-workflow.yml 
    with: 
      environment: Dev
      
  Call-Prod-deploy-workflow:
    
    uses: ./.github/workflows/Deploy-workflow.yml 
    with: 
     environment: Prod

  
