name: Deploy Workflow

on:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    outputs:
      JSON_CONTENT: ${{ steps.get-json-content.outputs.new_content }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  
      - name: Get JSON content
        id: get-json-content
        run: |
          echo '::set-output name=new_content::$(cat job_dependencies.json)'

  matrix_job_test:
    name: Matrix job test
    runs-on: ubuntu-latest
    needs: test_job
    strategy:
      matrix:
        include: ${{fromJson(needs.test_job.outputs.JSON_CONTENT)}}
    steps:
      - run: |
          echo $ENV_NAME
          echo "The necessary output is: $ENV_NAME"  # Print the necessary output
        env:
          ENV_NAME: ${{ matrix.env }}
