name: Deploy Workflow

on:
  workflow_dispatch:
    

jobs:
  copy_files:
    runs-on: ubuntu-latest
    #env:
      #clientfile: "./job_dependencies/job_dependencies.json"
    outputs:
      env: ${{ steps.set-matrix.outputs.envi }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  
 
      - name: Copy Job Dependencies
        run: |
          mkdir -p job_dependencies  
          cp .github/job_dependencies.json job_dependencies/  
      - name: Listing the directory
        run: ls -R 
      - name: List Job Dependencies
        run: |
           cat job_dependencies/job_dependencies.json
      - name: Set matrix data
        id: set-matrix
        run: |
          echo "envi=$(jq -r .env job_dependencies/job_dependencies.json)" >> $GITHUB_OUTPUT
      - name: Check env value
        run: echo $env
  print:
    runs-on: ubuntu-latest
    needs: copy_files
    strategy:
      matrix:
        component: ${{ fromJSON(needs.copy_files.outputs.envi) }}
      fail-fast: false
    env:
      title: ${{ matrix.component.env }}
      
    steps:
      - name: Check env value from print
        run: |
          echo $title
