name: Deploy Workflow
on:
   workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed

jobs:
  approval:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.approval.outputs.environment }}
    steps:
      - name: Manual Approval
        id: approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: mspriya92
          minimum-approvals: 1
          issue-title: "Deploying the java web app to Tomcat"
          issue-body: "Please approve or deny the deployment"
          exclude-workflow-initiator-as-approver: false
          timeout-minutes: 5  # Set a 2-minute time limit for the approval process
      - name: Select Environment for Deployment
        if: steps.approval.outputs.approved == 'true'
        run: |
          echo "Please select the environment for deployment:"
          echo "1. Dev"
          echo "2. Prod"
          read -p "Enter the number for the desired environment: " choice
          if [ $choice -eq 1 ]; then
            echo "environment=dev"  # Set the environment to Dev based on the selection
          elif [ $choice -eq 2 ]; then
            echo "environment=prod"  # Set the environment to Prod based on the selection
          else
            echo "Invalid choice. Please select 1 for Dev or 2 for Prod."
          fi
     
  deploy-dev:
    needs: approval
    runs-on: self-hosted
    if: needs.approval.outputs.environment == 'dev'
    steps:
      - name: Download workflow artifact (Dev)
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: NewBuild.yml
          repo: DigitalSoftwareInc/TicketReservation
          name: web-app
          path: D:/github/
      - name: Deploy to Tomcat
        if: steps.approval.outputs.approved == 'true'
        run: cp D:/github/*.war "C:/Program Files/Apache Software Foundation/Tomcat 10.1/webapps/"

  deploy-prod:
    needs: approval
    runs-on: self-hosted
    if: needs.approval.outputs.environment == 'prod'
    steps:
      - name: Copy artifacts to production VM
        run: scp -r D:/github/*.war 10459@192.168.0.175:/D/github/
