name: Deploy-workflow
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev, Prod, or Prod1)?'
        required: true
        type: string
jobs:
  Deploy-Dev:
    
    environment: Dev
    runs-on: self-hosted
    steps:
      - name: Printing mgs
        run: echo "Deployed in Dev"

  Deploy-Prod:
    runs-on: ubuntu-latest
    needs: ${{ Deploy-Dev }}
    steps:
      - name: Set Variable
        uses: deep-mm/set-variables@v1.0
        with:
           job_dependencies: 'variables' #Dont write .json here
      - name: Prod Deployment
        run: echo "Deploying to Prod environment"
        
  Deploy-Prod1:
    runs-on: ubuntu-latest
    needs: ${{ Deploy-Prod }}
    steps:
      - name: Set Variable
        uses: deep-mm/set-variables@v1.0
        with:
           job_dependencies: 'variables' #Dont write .json here
      - name: Prod1 Deployment
        run: echo "Deploying to Prod1 environment"
