name: Deploy-workflow
on:
  workflow_dispatch:
  
  workflow_call:
     inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string

jobs:
  Echo-event-name:
    runs-on: ubuntu-latest
    steps:
      - name: Printing mgs
        run: 
            # echo github.event_name
             echo ${{ github.event_name }}
  Deploy-Call-Dev:
    if: github.event_name == 'workflow_call' 
    environment: Dev
    runs-on: self-hosted
    steps:
      - name: Printing mgs
        run: echo "Deployed in workflowcall Dev"

  

  
  Deploy-Dev:
    if: github.event_name == 'workflow_dispatch'
    environment: Dev
    runs-on: self-hosted
    steps:
      - name: Printing mgs
        run: echo "Deployed in Dev"

  
