name: Deploy Workflow
on:
  workflow_dispatch:
jobs:
  copy_files:
    runs-on: ubuntu-latest
    #env:
      #clientfile: "./job_dependencies/job_dependencies.json"
    outputs:
      component: ${{ steps.set-matrix.outputs.env }}
      deploy_status: ${{ steps.set-deploy-status.outputs.deploy_status }}
    steps:
      - name: Checkouts Repository
        uses: actions/checkout@v3  
      - name: Listing the directory
        run: ls -R 
      - name: List Job Dependencies
        run: |
           cat job_dependencies/job_dependencies.json
      - name: Set matrix data
        id: set-matrix
        run: |
          echo "env=$(jq -r .env job_dependencies/job_dependencies.json)" >> $GITHUB_ENV
      - name: Check env value
        run: echo $component
        
      - name: Deploy Step
        id: deploy-step
        run: |
          # Run the deployment command or script
          ./deploy.sh

            # Check if the deployment command succeeded
          if [ $? -ne 0 ]; then
             echo "Deployment failed!"
             exit 1
          else
            echo "Deployment succeeded!"
          fi
      - name: Set deploy status output
        id: set-deploy-status   # You should set an id here to capture output
        run: |
          echo "deploy_status=${{ job.status }}" >> $GITHUB_ENV
