name: Checking terraform
on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment'
        type: string
    secrets:
      ADMIN_USERNAME:
        required: true  # Accepts inherited secrets

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}  # Uses caller's env name
    steps:
      - run: |
           echo "Using secret: ${{ secrets.ADMIN_USERNAME }}"

  call-test1:
    needs: deploy
    uses: ./.github/workflows/test1.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}  # Forward secret
