name: Deploy-workflow
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev, Prod, or Prod1)?'
        required: true
        type: string
jobs:
  Deploy-Dev:
    environment: Dev
    runs-on: self-hosted
    steps:
      - name: Printing mgs
        run: echo "Deployed in Dev"

  Deploy-Prod:
    runs-on: self-hosted
    needs: ${{ matrix.needs }}
    strategy:
      matrix:
        environment: ['Prod']
        needs: ['Deploy-Dev']
    steps:
      - name: Printing mgs
        run: echo "Deployed in prod"

  Deploy-Prod1:
    runs-on: self-hosted
    needs: ${{ matrix.needs }}
    strategy:
      matrix:
        environment: ['Prod1']
        needs: ['Deploy-Prod']
    steps:
      - name: Printing mgs
        run: echo "Deployed in prod1"
