name: Deploy-workflow
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
  workflow_call:
        
jobs:
  Deploy-Dev:
    runs-on: self-hosted
    environment: Dev
    if: ${{ github.event.inputs.releaseType == 'Dev' }}
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: Build Workflow.yml
          repo: mspriya92/TrainBook
          name: web-app
          path: D:/github/
      - name: Deploy to Tomcat
        run: cp D:/github/*.war "C:/Program Files/Apache Software Foundation/Tomcat 10.1/webapps/"
  Deploy-Prod:
    runs-on: self-hosted
    if: ${{ github.event.inputs.releaseType == 'Prod' }}
    steps:
      - name: Printing mgs
        run: echo "Deployed in prod"
