name: Deploy Workflow
 
on:
  workflow_dispatch:
    inputs:
      trigger_job1:
        description: 'Trigger Job 1'
        default: true
 
jobs:
  Deploy-Dev:
    runs-on: ubuntu-latest
    environment: Dev
    if: ${{ github.event.inputs.trigger_job1 == 'true' }}
    steps:
      - name: Job 1
        run: echo "Running Job 1 for dev environment"
 
  Deploy-Caller-Dev:
    runs-on: ubuntu-latest
    environment: Dev
    if: ${{ github.event.inputs.trigger_job1 !='true' }}
    steps:
      - name: Job 2
        run: echo "Running Job 2 for caller-dev environment"
