name: Deploy Component New
on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
      environment:
        type: string
        required: true
      runner:
        type: string
        required: true
    outputs:        
      compstatus:
        value: ${{ jobs.component-status.outputs.output1 }}
    
jobs:
  create-component-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 step
        id: step1
        run: |
          echo "firstword=job1 from deploy component" 

  deploy-to-AzService:
    runs-on: ubuntu-latest
    needs: create-component-matrix
    steps:
      - name: Job 2 step
        id: step2  # We add an ID for job2
        run: |
          echo "secondword=job2 from deploy component" 
  
  component-status:
    runs-on: ubuntu-latest
    needs: [create-component-matrix, deploy-to-AzService]
    outputs:
      output1: ${{ steps.report-status.outputs.compjob }}
    steps:
      - name: Report job statuses
        id: report-status
        run: |
          # PowerShell script to loop through job statuses dynamically and format the output
          $jobNames = @("create-component-matrix", "deploy-to-AzService")
          $compjob = ""
          
          foreach ($job in $jobNames) {
            # Get the result of each job (success, failure, skipped)
            $status = "${{ needs.$job.result }}"
            
            # Format the job status in the required form
            $compjob += "$job status: $status, "
          }
          
          # Trim the trailing comma and space
          $compjob = $compjob.TrimEnd(", ")

          # Output the final result to GitHub Actions
          echo "compjob=$compjob" >> $GITHUB_OUTPUT
