name: Deploy Component

on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
      environment:
        type: string
        required: true
      runner:
        type: string
        required: true
    outputs:
      compstatus1:
        description: "First output from the component"
        value: ${{ jobs.component-status.outputs.output1 }}
      compstatus2:
        description: "Second output from the component"
        value: ${{ jobs.component-status.outputs.output2 }}
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 step
        id: step1
        run: |
          echo "firstword=job1 from deploy component" 

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2 step
        id: step2  # We add an ID for job2
        run: |
          echo "secondword=job2 from deploy component" 
  
  component-status:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    outputs:
      output1: ${{ steps.report-status.outputs.compjob1 }}
      output2: ${{ steps.report-status.outputs.compjob2 }}
    steps:
      - name: Report job statuses
        id: report-status
        run: |
          #echo "compjob1=${{ needs.job1.result }}" >> $GITHUB_OUTPUT
          echo "compjob1=success check" >> $GITHUB_OUTPUT
          echo "compjob2=${{ needs.job2.result }}" >> $GITHUB_OUTPUT
            
 
