name: Deploy Phase
on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
      environment:
        type: string
        required: true
      runner:
        type: string
        required: true
    outputs:
      comp status1:
        description: "First output from the component"
        value: ${{ jobs.report-component-job-status.outputs.output1 }}
      comp status2:
        description: "Second output from the component"
        value: ${{ jobs.report-component-job-status.outputs.output2 }}
      phase status1:
        description: "First output from the component"
        value: ${{ jobs.phase-status.outputs.phase1op }}
      phase status2:
        description: "First output from the component"
        value: ${{ jobs.phase-status.outputs.phase2op }}
jobs:
  Phase1:
    if: ${{ ! contains(inputs.component, 'fullstack') }}
    uses: ./.github/workflows/deploy-component.yml
    with: 
      component: ${{ inputs.component }}
      environment: ${{ inputs.environment }}
      runner: ${{ inputs.runner }}

  
  Phase2:
    if: ${{  inputs.component == 'fullstack' }}
    uses: ./.github/workflows/deploy-component.yml
    with: 
      component: ${{ inputs.component }}
      environment: ${{ inputs.environment }}
      runner: ${{ inputs.runner }}
      
  phase-status:
    needs: [Phase1, Phase2]
    runs-on: ubuntu-latest
    outputs: 
      phase1op: ${{ needs.report.outputs.Phase1status}}
      phase2op: ${{ needs.report.outputs.Phase2status}}
    steps:
      - name: Report job statuses
        id: report
        run: |
          echo "Phase1status: ${{ needs.Phase1.result }}"
          echo "Phase2status: ${{ needs.Phase2.result }}"
         
