name: Deploy Workflow
on:
  workflow_dispatch

jobs:
approval:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      environment: ${{ steps.approval.outputs.environment }}
    steps:
      - name: Manual Approval
        id: approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: mspriya92
          minimum-approvals: 1
          issue-title: "Deploying the java web app to Tomcat"
          issue-body: "Please approve or deny the deployment"
          exclude-workflow-initiator-as-approver: false
          timeout-minutes: 2  # Set a 2-minute time limit for the approval process
      - name: Set environment
        run: echo "environment=dev"  
        if: steps.approval.outputs.approved == 'true'
      - name: Set environment
        run: echo "environment=prod"  
        if: steps.approval.outputs.approved == 'false'
deploy-dev:
  needs: approval
  runs-on: self-hosted
  if: needs.approval.outputs.environment == 'dev'
  steps:
    - name: Download workflow artifact (Dev)
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: NewBuild.yml
        repo: DigitalSoftwareInc/TicketReservation
        name: web-app
        path: D:/github/
    - name: Deploy to Tomcat
      if: steps.approval.outputs.approved == 'true'
      run: cp D:/github/*.war "C:/Program Files/Apache Software Foundation/Tomcat 10.1/webapps/"

  deploy-prod:
    needs: approval
    runs-on: self-hosted
    if: needs.approval.outputs.environment == 'prod'
    steps:
      - name: Download workflow artifact (Prod)
        uses: dawidd6/action-download-artifact@v3
        with:
		      github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: NewBuild.yml
          repo: DigitalSoftwareInc/TicketReservation
          name: web-app
          path: D:/github/
          
