name: Deploy Workflow
 
on:
  workflow_dispatch:
        
  workflow_call:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string

jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get build version from JSON
        run: |
          build_version=$(jq -r '.build_version' ./job_dependencies.json)
          echo "Build version:${{ matrix.build_version }}"
  Deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    if: ${{ github.event.inputs.environment == ' ' }}
    steps:
      - name: Job 1
        run: echo "Running Job 1 for ${{ github.event.inputs.environment }} environment"
      
 
  
      
  
 
