name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string

jobs:
  builder:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix data
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(echo '${{ toJson(matrix.cfg) }}' | tr -d ' ')"
   
  runner:
    needs: builder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: ${{fromJson(needs.builder.outputs.matrix)}}
        client: ${{fromJson(needs.builder.outputs.matrix)}}
    steps:
      - name: Download Binary
        run: |
          # Add the command to download the binary
      - name: Run Server Against Client
        run: |
          # Add the command to run the server against the client
