name: Deploy Component New
on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
      environment:
        type: string
        required: true
      runner:
        type: string
        required: true
    outputs:        
      compstatus:
        value: ${{ jobs.component-status.outputs.output1 }}
    
jobs:
  create-component-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 step
        id: step1
        run: |
          echo "firstword=job1 from deploy component" 

  deploy-to-AzService:
    runs-on: ubuntu-latest
    needs: create-component-matrix
    steps:
      - name: Job 2 step
        id: step2  # We add an ID for job2
        run: |
          echo "secondword=job2 from deploy component" 
  
  component-status:
    runs-on: ubuntu-latest
    needs: [create-component-matrix, deploy-to-AzService]
    outputs:
      output1: ${{ steps.report-status.outputs.compjob }}
    steps:
      - name: Report job statuses
        id: report-status
        run: |
          # Initialize an empty JSON object
          statuses="{}"
          
          # Collect job statuses (hardcoded for now)
          job1_status="${{ needs.create-component-matrix.result }}"
          job2_status="${{ needs.deploy-to-AzService.result }}"

          # Dynamically add job statuses to the JSON object using jq
          statuses=$(echo $statuses | jq --arg job1 "$job1_status" --arg job2 "$job2_status" \
            '. + {create-component-matrix: $job1, deploy-to-AzService: $job2}')

          # Set the final result as the output
          echo "compstatus=$statuses" >> $GITHUB_OUTPUT
