name: Deploy Component New

on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
      environment:
        type: string
        required: true
      runner:
        type: string
        required: true
    outputs:
      compstatus:
        value: ${{ jobs.collect-status.outputs.all_statuses }}

jobs:
  create-component-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 step
        run: echo "firstword=job1 from deploy component"

  deploy-to-AzService:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2 step
        run: echo "secondword=job2 from deploy component"

  collect-status:
    runs-on: ubuntu-latest
    if: always()  # Ensures this runs even if some jobs fail
    steps:
      - name: Get Job Statuses from GitHub API
        id: get_status
        run: |
          STATUSES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs" | \
            jq -r '.jobs | map({(.name): .conclusion}) | add')

          echo "Statuses: $STATUSES"
          echo "statuses=$STATUSES" >> "$GITHUB_ENV"
        shell: bash

      - name: Save Job Status as Output
        id: save_output
        run: echo "all_statuses=${{ env.statuses }}" >> "$GITHUB_OUTPUT"
