name: Deploy-workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: environment
  workflow_call:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
jobs:
  Deploy-Dev:
    if: ${{ github.event.inputs.environment == 'Dev' }}
    runs-on: self-hosted
    environment: Dev
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: Build Workflow.yml
          repo: mspriya92/TrainBook
          name: web-app
          path: D:/github/
      - name: Deploy to Tomcat
        run: cp D:/github/*.war "C:/Program Files/Apache Software Foundation/Tomcat 10.1/webapps/"

            
  
  Deploy-Prod:
    needs:  Deploy-Dev
    runs-on: self-hosted
    if: ${{ github.event.inputs.environment == 'Prod' }}
    environment: Prod
    steps:
      - name: Printing mgs
        run: echo "Deployed in prod"
