name: Tomcat deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: C:\Users\10443\actions-runner\artifacts  # Replace with the actual path to the artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: C:\Users\10443\actions-runner\downloadedartifacts  # Specify the path to download the artifact
      - name: Tomcat deploy
        run: curl -v -u ${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }} -T "C:\Users\10443\actions-runner\downloadedartifacts\TrainBook-1.0.0-SNAPSHOT.war" 'http://localhost:8080/manager/text/deploy?path=/trainbook-GithubAction'
