name: Deploy-workflow
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev, Prod, or Prod1)?'
        required: true
        type: string
jobs:
  Deploy-Dev:
    
    environment: Dev
    runs-on: self-hosted
    steps:
      - name: Printing mgs
        run: echo "Deployed in Dev"

  Deploy-Prod:
    runs-on: ubuntu-latest
    needs: ${{ fromJson(needs_dev) }}
    steps:
      - name: Prod Deployment
        run: echo "Deploying to Prod environment"

  Deploy-Prod1:
    runs-on: ubuntu-latest
    needs: ${{ fromJson(needs_prod) }}
    steps:
      - name: Prod1 Deployment
        run: echo "Deploying to Prod1 environment"

  read_json:
    runs-on: ubuntu-latest
    outputs:
      needs_dev: ${{ steps.parse.outputs.needs_dev }}
      needs_prod: ${{ steps.parse.outputs.needs_prod }}
    steps:
      - name: Read JSON file
        run: |
          echo "::set-output name=needs_dev::$(cat job_dependencies.json | jq -r '.needs_dev')"
          echo "::set-output name=needs_prod::$(cat job_dependencies.json | jq -r '.needs_prod')"
