name: Deploy-workflow
on:
  workflow_call:
    
     inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
  workflow_dispatch:

jobs:
  Deploy-Call-Dev:
    if: ${{ github.event.inputs.environment }} == 'Dev' 
    environment: Dev
    runs-on: self-hosted
    steps:
      - name: Printing mgs
        run: echo "Deployed in workflowcall Dev"
  
  Deploy-Dev:
    if: github.event.name == 'workflow_dispatch'
    environment: Dev
    runs-on: self-hosted
    steps:
      - name: Printing mgs
        run: echo "Deployed in Dev"

  
