name: Deploy Workflow

on:
  workflow_dispatch:
    

jobs:
  copy_files:
    runs-on: ubuntu-latest
   
    outputs:
      envi: ${{ steps.set-matrix.outputs.envi }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  
 
      
      - name: Set matrix data
        id: set-matrix
        run: |
          echo "envi-info=`perl -pe 's/\s+//g' ./job_dependencies.json`" >> $GITHUB_OUTPUT
          echo "$envi-info"

  print:
    runs-on: ubuntu-latest
    needs: copy_files
    strategy:
      matrix:
        component: ${{ fromJSON(needs.copy_files.outputs.envi) }}
      fail-fast: false
    env:
      env: ${{ matrix.component.env }}
      
    steps:
      - name: Check env value from print
        run: |
          
          echo $env
          - name: Debug fromJSON output
          
          echo "fromJSON output: ${{ fromJSON(needs.copy_files.outputs.envi) }}"

 
