name: Deploy Workflow

on:
  workflow_dispatch:
    

jobs:
  copy_files:
    runs-on: ubuntu-latest
    env:
      clientfile: "job_dependencies.json"
    outputs:
      env: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  
 
      #- name: Copy Job Dependencies
        #run: |
          #mkdir -p job_dependencies  
          #cp .github/job_dependencies.json job_dependencies/  
      #- name: Listing the directory
       # run: ls -R 
     # - name: List Job Dependencies
      #  run: |
       #    cat job_dependencies/job_dependencies.json
      - name: Set matrix data
        id: set-matrix
        run: |
          echo "ENV=$(cat job_dependencies.json)" >> $GITHUB_ENV
          #echo "$GITHUB_OUTPUT"
  
  print:
    runs-on: ubuntu-latest
    needs: copy_files
    strategy:
      matrix:
        env: ${{fromJson(env.ENV)}}
    steps:
      - run: echo ${{ matrix.env }}

