name: Deploy Workflow

on:
  workflow_dispatch:
    

jobs:
  test_job:
    runs-on: ubuntu-latest
   
    outputs:
      JSON_CONTENT: ${{ steps.get-json-content.outputs.new_content }} # Correct output variable name
       
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  
 
      - name: Get JSON content
        id: get-json-content
        run: |
          echo 'JSON_CONTENT<<EOF' >> $GITHUB_ENV
          cat job_dependencies.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

  matrix_job_test:
    name: Matrix job test
    runs-on: ubuntu-latest
    needs: test_job
    strategy:
      matrix:
        include: ${{ fromJSON(needs.test_job.outputs.JSON_CONTENT) }} # Access correct output variable
    steps:
      - run: |
          echo $ENV_NAME
          
        env:
          ENV_NAME: ${{ matrix.env }}
