name: Deploy Comp1

on:
 #push: 
 workflow_call:
    inputs:
      component:
        type: string
        required: true
      environment:
        type: string
        required: true
      runner:
        type: string
        required: true
    #outputs:
      #compstatus:
        #value: ${{ jobs.component-status.outputs.output1 }}
        #value: ${{ jobs.collect-status.outputs.output1 }}
    
jobs:
  create-component-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 step
        id: step1
        run: |
          echo "firstword=job1 from deploy component" 

  deploy-to-AzService:
    runs-on: ubuntu-latest
    needs: create-component-matrix
    steps:
      - name: Job 2 step
        id: step2  # We add an ID for job2
        run: |
          echo "secondword=job2 from deploy component" 

      - name: Using workflow from another repo
        uses: actions/checkout@v4
        with:
          #repository: SphereTechSol/sb
          repository: ${{ github.repository_owner }}/sb
          ref: ${{ steps.extract-branch.outputs.sb_branchname }}
          token: ${{ secrets.SB_REPO_TOKEN }}
          path: sb
