name: Deploy Workflow

on:
  workflow_dispatch:
    

jobs:
  copy_files:
    runs-on: ubuntu-latest
    env:
      clientfile: "./job_dependencies/job_dependencies.json"
    outputs:
      env: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  
 
      - name: Copy Job Dependencies
        run: |
          mkdir -p job_dependencies  
          cp .github/job_dependencies.json job_dependencies/  
      - name: Listing the directory
        run: ls -R 
      - name: List Job Dependencies
        run: |
           cat job_dependencies/job_dependencies.json
      - name: Set matrix data
        id: set-matrix
        run: |
          echo "env=$(perl -pe 's/\s+//g' './job_dependencies/job_dependencies.json')" >> "$GITHUB_OUTPUT"
          echo "$GITHUB_OUTPUT"
  
  Print:
    runs-on: ubuntu-latest
    needs: copy_files
    steps:
      - name: Debug JSON Data
        run: |
          cat ${{ needs.copy_files.outputs.env }}
      - name: Print JSON Data
        run: |
          echo "Parsed JSON: ${{ fromJson(needs.copy_files.outputs.env) }}"
