name: Deploy Component

on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
      environment:
        type: string
        required: true
      runner:
        type: string
        required: true
    
jobs:
  job1:
    runs-on: ubuntu-latest
      # We add an ID for the job
    steps:
      - name: Job 1 step
        id: step1
        run: |
          echo "firstword=job1 from deploy component" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2 step
        id: step2  # We add an ID for job2
        run: |
          echo "secondword=job2 from deploy component" >> $GITHUB_OUTPUT

  report-job-status:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    outputs:
      deploy-component-status: ${{ steps.report-status.outputs.status }}  # Pass the status as output
    steps:
      - name: Aggregate and report status
        id: report-status
        run: |
          echo "status=success" >> $GITHUB_OUTPUT         
 
