name: Caller-workflow
on:
  workflow_call:
   
        
jobs:
  Call-workflow-for-deploy:
   runs-on: ubuntu-latest
   steps:
     - name: checking the value 
       run: echo "Initial value:${{ inputs.initial }}"
    
   
    
 
  
