name: Deploy-workflow
on:
  workflow_dispatch:
    
  workflow_call:
     inputs:
      # New input to control job selection
      deploy_target:
        description: 'Specify the deployment environment (Call-Dev or call-prod or call-prod1)?'
        required: true
        type: string

jobs:
  Deploy-Call-Dev:
    if: ${{ github.event_name == 'workflow_call' && github.event.inputs.deploy_target == 'Call-Dev' }} }}
    runs-on: self-hosted
    environment: Dev
    steps:
      - name: Printing mgs
        run: echo "Deployed in workflowcall Dev"

  Deploy-Call-Prod:
    if: ${{ github.event_name == 'workflow_call' && github.event.inputs.deploy_target == 'call-prod' }} }}
    runs-on: self-hosted
    needs: Deploy-Call-Dev
    environment: Prod
    steps:
      - name: Printing mgs
        run: echo "Deployed in workflowcall prod"

  Deploy-Call-Prod1:
    if: ${{ github.event_name == 'workflow_call' && github.event.inputs.deploy_target == 'call-prod1' }} }}
    runs-on: self-hosted
    needs: Deploy-Call-Prod
    steps:
      - name: Printing mgs in prod1 Branch
        run: echo "Deployed in workflowcall prod1 env"
  Deploy-Dev:
    #if: ${{ github.event_name == 'workflow_dispatch' }}
    environment: Dev
    runs-on: self-hosted
    steps:
      - name: Printing mgs
        run: echo "Deployed in Dev"

  Deploy-Prod:
    #if: ${{ github.event_name == 'workflow_dispatch' }}
    environment: Prod
    runs-on: self-hosted
    needs: Deploy-Dev
    steps:
      - name: Printing mgs
        run: echo "Deployed in prod"

  Deploy-Prod1:
    #if: ${{ github.event_name == 'workflow_dispatch' }}
    environment: Prod1
    runs-on: self-hosted
    needs: Deploy-Prod
    steps:
      - name: Printing mgs
        run: echo "Deployed in prod1"

  
