name: Deploy-workflow
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev, Prod, or Prod1)?'
        required: true
        type: string
jobs:
  Deploy-Dev:
    runs-on: self-hosted
    environment:
      name: Dev
    steps:
      - name: Printing mgs
        run: echo "Deployed in Dev"

  Deploy-Prod:
    runs-on: self-hosted
    needs: ${{ needs_dev }}
    environment:
      name: Prod
    steps:
      - name: Printing mgs
        run: echo "Deployed in prod"

  Deploy-Prod1:
    runs-on: self-hosted
    needs: ${{ needs_prod }}
    environment:
      name: Prod1
    steps:
      - name: Printing mgs
        run: echo "Deployed in prod1"

env:
  needs_dev: Deploy-Dev
  needs_prod: Deploy-Prod
