name: Deploy Component

on:
 #push: 
 workflow_call:
    inputs:
      component:
        type: string
        required: true
      environment:
        type: string
        required: true
      runner:
        type: string
        required: true
    outputs:
      #compstatus1:
        #description: "First output from the component"
        #value: ${{ jobs.component-status.outputs.output1 }}
      #compstatus2:
        #description: "Second output from the component"
        #value: ${{ jobs.component-status.outputs.output2 }}
      compstatus:
        #value: ${{ jobs.component-status.outputs.output1 }}
        value: ${{ jobs.collect-status.outputs.all_statuses }}
    
jobs:
  create-component-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 step
        id: step1
        run: |
          echo "firstword=job1 from deploy component" 

  deploy-to-AzService:
    runs-on: ubuntu-latest
    needs: create-component-matrix
    steps:
      - name: Job 2 step
        id: step2  # We add an ID for job2
        run: |
          echo "secondword=job2 from deploy component" 
  
  #component-status:
    #runs-on: ubuntu-latest
    #needs: [create-component-matrix, deploy-to-AzService]
    #needs: [job1, job2]
    #outputs:
      #output1: ${{ steps.report-status.outputs.compjob }}
    #steps:
      #- name: Report job statuses
        #id: report-status
        #run: |
          #compjob="job1 status: ${{ needs.job1.result }}, "
          #compjob+="job2 status: ${{ needs.job2.result }}"
          #compjob="create-component-matrix status: ${{ needs.create-component-matrix.result }}, "
          #compjob+="deploy-to-AzService status: ${{ needs.deploy-to-AzService.result }}"
          #echo "compjob=$compjob" >> $GITHUB_OUTPUT
  collect-status:
    needs: [create-component-matrix, deploy-to-AzService]
    runs-on: ubuntu-latest
    if: always()  # Ensures this runs even if some jobs fail
    steps:
      - name: Get Job Statuses from GitHub API
        id: get_status
        run: |
          WORKFLOW_NAME="${{ github.workflow }}"  # Get current workflow name
          STATUSES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs" | \
          jq -r --arg WORKFLOW_NAME "$WORKFLOW_NAME" \
          '[.jobs[] | select(.workflow_name == $WORKFLOW_NAME and .name != "collect-status") | "\(.name) status: \(.conclusion // "in_progress")"] | join(", ")')
    
          echo "Filtered statuses: $STATUSES"
          echo "statuses=$STATUSES" >> "$GITHUB_ENV"
        shell: bash
          
      - name: Save Job Status as Output
        id: save_output
        run: echo "all_statuses=${{ env.statuses }}" >> "$GITHUB_OUTPUT"
