name: Deploy-workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: environment
  workflow_call:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
jobs:
  Deploy-Dev:
    if: ${{ github.event.inputs.environment == 'Dev' }}
    runs-on: self-hosted
    environment: Dev
    steps:
      - name: Printing mgs
        run: echo "Deployed in Dev"
  
  Deploy-Prod:
    needs: Deploy-Dev
    runs-on: self-hosted
    if: ${{ github.event.inputs.environment == 'Prod' }}
    environment: Prod
    steps:
      - name: Printing mgs
        run: echo "Deployed in prod"
