name: Deploy Component

on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
      environment:
        type: string
        required: true
      runner:
        type: string
        required: true
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 step
        id: step1
        run: |
          echo "firstword=job1 from deploy component" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2 step
        id: step2  # We add an ID for job2
        run: |
          echo "secondword=job2 from deploy component" >> $GITHUB_OUTPUT
  
  report-component-job-status:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Report job statuses
        id: report-status
        run: |
          echo "component job1 status: ${{ needs.job1.result }}"
          echo "component job1 status: ${{ needs.job2.result }}"
            
 
