name: Deploy-workflow
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev, Prod, or Prod1)?'
        required: true
        type: string
jobs:
  Deploy-Dev:
    
    environment: Dev
    runs-on: self-hosted
    steps:
      - name: Printing mgs
        run: echo "Deployed in Dev"

  Deploy-Prod:
    environment: Prod
    runs-on: ubuntu-latest
    needs: ${{ fromJson(needs-prod) }}
    steps:
      - name: Prod Deployment
        run: echo "Deploying to Prod environment"

  Deploy-Prod1:
    environment: Prod1
    runs-on: ubuntu-latest
    needs: ${{ fromJson(needs-prod1) }}
    steps:
      - name: Prod1 Deployment
        run: echo "Deploying to Prod1 environment"

  
  read_json:
    runs-on: ubuntu-latest
    outputs:
      needs-prod: ${{ steps.read.outputs.needs-prod }}
      needs-prod1: ${{ steps.read.outputs.needs-prod1 }}
    steps:
      - name: Read JSON file
        id: read
        run: |
          echo "::set-output name=needs-prod::$(cat job_dependencies.json )"
          echo "::set-output name=needs-prod1::$(cat job_dependencies.json )" 
