name: Deploy job

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
 deploy:
      runs-on: self-hosted
      steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: web-app
          path: D:\github\
