name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        default: 'Dev'

