name: Deploy Workflow
on:
  workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        default: 'Dev'

jobs:
  Deploy-Dev:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: Download workflow artifact
        uses: actions/download-artifact@v2
        with:
          name: web-app
          path: D:/github/
      - name: Deploy to Tomcat
        run: cp D:/github/*.war "C:/Program Files/Apache Software Foundation/Tomcat 10.1/webapps/"
