name: Deploy Workflow

on:
  workflow_dispatch:

jobs:
  copy_files:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.set-matrix.outputs.env }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Copy Job Dependencies
        run: |
          mkdir -p job_dependencies
          cp .github/job_dependencies.json job_dependencies/
      - name: Listing the directory
        run: ls -R
      - name: List Job Dependencies
        run: |
          cat job_dependencies/job_dependencies.json
      - name: Set matrix data
        id: set-matrix
        run: |
          DATA=$(jq -c '.[] | .env' < job_dependencies/job_dependencies.json)
          echo "env=$DATA" >> $GITHUB_ENV

  print:
    runs-on: ubuntu-latest
    needs: copy_files
    strategy:
      matrix:
        env: ${{fromJson(needs.copy_files.outputs.env)}}
    steps:
      - run: echo ${{ matrix.env }}
