name: Deploy Workflow
 
on:
  workflow_dispatch:
        
  workflow_call:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Dev
    if: ${{ github.event.inputs.environment == '' }}
    steps:
      - name: Job 1
        run: echo "Running Job 1 for ${{ github.event.inputs.environment }} environment"
  
