name: DockerBuild

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Creates stagin directory and copy .war
        run: |
          mkdir staging
          cp target/*.war staging/
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-app
          path: staging
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mspriya92/java-web-app:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull application image
        run: docker pull mspriya92/java-web-app:latest  # Or another Windows-compatible image (adjust tag if needed)
      - name: Create docker network
        run: docker network create my-network
      - name: Pull tomcat image
        run: docker pull bitnami/tomcat:latest
      - name: Run Tomcat container
        run: docker run -d --name tomcat-container --network my-network -p 8080:8080 bitnami/tomcat:latest  # Detached mode (-d), expose port
             
      - name: Deploy your application  
        run: docker run -d --name app-container --network my-network -v staging/web-app.war:/usr/local/tomcat/webapps/web-app.war mspriya92/java-web-app:latest

             

      - name: Wait for tomcat to deploy
        run: sleep 30
      - name: Check if tomcat is running
        run: docker exec tomcat-container curl -I http://localhost:8080/myapp || exit 1  
      - name: Check if my app is deployed
        run: docker exec tomcat-container curl -I http://localhost:8080/myapp || exit 1
       
      #- name: Run your application container
        #run: docker run -d -p 8081:8080 mspriya92/java-web-app:latest  # Detached mode (-d), map port (adjust if needed)
        #run: docker run -d -p 8080:8080 -v mspriya92/java-web-app:latest:/usr/local/tomcat/webapps bitnami/tomcat:latest
        #run: docker run -d -p 8080:8080 -v java-web-app:/usr/local/tomcat/webapps bitnami/tomcat:latest
     
