name: EphemeralRunnerTest

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ARC-Runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Display message
        run: echo "Runner is operational!"
