name: filtercheck
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
      component:
        description: 'Choose the required component'
        required: true
        type: choice
        options:
          - com1
          - com2
          - com3
 
jobs:
  copy_files:
    runs-on: ubuntu-latest
    outputs:
      components-info: ${{ steps.set-matrix.outputs.filtered-components }}
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Set matrix data
        id: set-matrix
        working-directory: ./job_dependencies
        run: |
          COMPONENT="$INPUT_component"
          VERSION=$(perl -ne '/"name":\s*"$COMPONENT"/ && /"version":\s*"([^"]+)"/ && print $1' job_dependencies.json)
          echo "::set-output name=filtered-components::{\"name\": \"$COMPONENT\", \"version\": \"$VERSION\"}"
      - name: Print filtered components
        run: |
          echo "Filtered Component Name: ${{ steps.set-matrix.outputs.filtered-components.name }}"
          echo "Filtered Component Version: ${{ steps.set-matrix.outputs.filtered-components.version }}"
 
  Comparison:
    runs-on: ubuntu-latest
    needs: copy_files
    continue-on-error: true
    strategy:
      matrix:
        components: ${{ fromJSON(needs.copy_files.outputs.components-info) }}
      fail-fast: false
      max-parallel: 1
 
    steps:
      - name: checking matrix value
        run: |
          echo "${{ matrix.components.name }}"
          echo "${{ matrix.components.version }}"
