name: Filtercheck
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
      Filters:
        description: 'Choose the required component'
        required: true
        type: choice
        options:
          - com1
          - com2
          - com3

jobs:

  copy_files:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      #components-info: ${{ steps.set-matrix.outputs.backend-components }}
      filter-info: ${{ steps.filter-step.outputs.filteredData }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      

      - name: Filtering JSON data
        id: filter-step
        working-directory: ./job_dependencies
        run: |
          #chosencomponents="${{ github.event.inputs.Filters }}"
          echo " filteredData=`cat ./job_dependencies.json | grep ${{ inputs. Filters }} -m1 -A5 |  perl -pe 's/\s+//g'`"  >> $GITHUB_OUTPUT
          #filteredData=$(jq -r --arg chosenCom "$chosencomponents" '.[] | select(.name == $chosenCom)' job_dependencies/job_dependencies.json)
         
    
          echo "$filteredData"
         
  Comparison:
    runs-on: ubuntu-latest
    needs: copy_files
    continue-on-error: true
    strategy:
      matrix:
        #components: ${{ fromJSON(needs.copy_files.outputs.components-info) }}
        filters: ${{ fromJSON(needs.copy_files.outputs.filter-info) }}
        #fail-fast: false
        #max-parallel: 1
    env:
      #name: ${{ matrix.components.name }}  # Access component name from matrix
      #version: ${{ matrix.components.version }}  # Access component version from matrix
      name1: ${{ matrix.filters.name }}
      version1: ${{ matrix.filters.version }}
      
    steps:
      - name: Checking matrix value
        run: |
          #echo "$name"
          #echo "$version"
          echo "$name1"
          echo "$version1"
