name: filtercheck

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
      Filter:
        description: 'Choose the filter to deploy (Dev or Prod)?'
        required: true
        type: choice
        options: [com1, com2, com3]

jobs:
  copy_files:
    runs-on: ubuntu-latest
    outputs:
      components-info: ${{ steps.set-matrix.outputs.backend-components }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set matrix data
        id: set-matrix
        working-directory: ./job_dependencies
        run: |
          FILTER=$INPUT_Filter
          BACKEND_COMPONENTS=$(perl -lne '/"name":\s*"$FILTER"/ && print' job_dependencies.json)
          echo "backend-components: $BACKEND_COMPONENTS"
          echo "::set-output name=backend-components::$BACKEND_COMPONENTS"
