name: filtercheck Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string

jobs:
  filter_json:
    runs-on: ubuntu-latest
    outputs:
      filtered-components: ${{ steps.filter-json.outputs.filtered-components }}

    steps:
      - name: Filter JSON
        id: filter-json
        run: |
          # Read the input filter value
          FILTER_VALUE=${{ github.event.inputs.environment }}

          # Filter the JSON based on the input filter using jq command
          FILTERED_JSON=$(jq --arg filter "$FILTER_VALUE" 'to_entries | map(select(.key == $filter)) | from_entries' ./job_dependencies/job_dependencies.json)

          # Set the output
          echo "::set-output name=filtered-components::$FILTERED_JSON"
          echo "Filtered JSON: $FILTERED_JSON"  # Output the filtered JSON for checking
