name: filtercheck

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
      Filter:
        description: 'Choose the filter to deploy (com1, com2, or com3)?'
        required: true
        type: string
        options:
          - com1
          - com2
          - com3

jobs:
  filter_json:
    runs-on: ubuntu-latest
    outputs:
      filtered-components: ${{ steps.filter-json.outputs.filtered-components }}

    steps:
      - name: Filter JSON
        id: filter-json
        #working-directory: ./job_dependencies
        run: |
          # Read the input filter value
          FILTER_VALUE=${{ github.event.inputs.Filter }}

          # Filter the JSON based on the input filter using Perl command
          FILTERED_JSON=$(perl -ne 'print if /"$FILTER_VALUE":/' ./job_dependencies/job_dependencies.json)

          # Set the output
          echo "::set-output name=filtered-components::$FILTERED_JSON"
          echo "Filtered JSON: $FILTERED_JSON"  # Output the filtered JSON for checking

  use_filtered_data:
    runs-on: ubuntu-latest
    needs: filter_json
    steps:
      - name: Use Filtered Data
        run: |
          echo "Filtered JSON: ${{ needs.filter_json.outputs.filtered-components }}"
