name: filtercheck Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
      filters:
        description: 'Choose the required Filter'
        required: true
        type: string  # Change the type to string as the options are strings

jobs:
  copy_files:
    runs-on: ubuntu-latest
    outputs:
      backend-components: ${{ steps.set-matrix.outputs.filteredData }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set matrix data
        id: set-matrix
        run: |
          filteredData=$(perl -lne 'print $1 if /"${{ github.event.inputs.filters }}"\s*:\s*"([^"]+)"/' job_dependencies.json)
          echo "filteredData=$filteredData" >> $GITHUB_OUTPUT  # Use $GITHUB_OUTPUT to set the environment variable
          echo "Filtered Data: $filteredData"  # Print the value of filteredData
  comparison:
    runs-on: ubuntu-latest
    needs: copy_files
    strategy:
      matrix:
        components: ${{fromJson(needs.copy_files.outputs.backend-components)}}
      fail-fast: false
      max-parallel: 1
    steps:
      - name: Checking matrix value
        run: |
          echo "Component: ${{ matrix.components }}"
