name: filtercheck

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
      Filter:
        description: 'Choose the filter to deploy (Dev or Prod)?'
        required: true
        type: choice
        options:
          - com1
          - com2
          - com3

jobs:
  copy_files:
    runs-on: ubuntu-latest
    outputs:
      filtered-components: ${{ steps.filter-json.outputs.filtered-components }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Filter JSON
        id: filter-json
        working-directory: ./job_dependencies
        run: |
          # Read the input filter value
          FILTER_VALUE=${{ github.event.inputs.Filter }}

          # Filter the JSON based on the input filter
          FILTERED_JSON=$(perl -ne 'print if /"component":\s*"$FILTER_VALUE"/' job_dependencies.json)

          # Set the output
          echo "::set-output name=filtered-components::$FILTERED_JSON"

      - name: Echo Filtered Components
        run: |
          echo "Filtered Components: ${{ steps.filter-json.outputs.filtered-components }}"

  comparison:
    runs-on: self-hosted
    needs: copy_files
    continue-on-error: true
    strategy:
      matrix:
        components: ${{ fromJSON(needs.copy_files.outputs.filtered-components) }}
      fail-fast: false
      max-parallel: 1

    steps:
      - name: checking matrix value
        run: |
          echo "Matrix Components: ${{ matrix.components }}"
