name: Basic workflow
 
on: 
  workflow_dispatch:
  workflow_call:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: What is the event?
      run: |
        if: github.event_name == 'workflow_dispatch'
          run: echo "This is triggered by workflow_dispatch"
          else if: github.event_name == 'workflow_call'
          run: echo "This is triggered by workflow_call"
          else
          run: echo "This is an unknown event"
