name: jsonfilter
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
      Filters:
        description: 'Choose the required component'
        required: true
        type: choice
        options:
          - com1
          - com2
          - com3
jobs:
  copy_files:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      components-info: ${{ steps.set-matrix.outputs.backend-components }}
      filtered-info: ${{ steps.filter-step.outputs.filteredData }}  # Corrected output name
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set matrix data
        id: set-matrix
        working-directory: ./job_dependencies
        run: |
          echo "backend-components=`perl -pe 's/\s+//g' job_dependencies.json`" >> $GITHUB_OUTPUT
          echo "$backend-components"
      - name: Filtering JSON data
        id: filter-step
        run: |
          chosencomponents="${{ github.event.inputs.Filters }}"
          
          filteredData=$(jq -c --arg chosenCom "$chosencomponents" '.[] | select(.name == $chosenCom) | tojson' job_dependencies/job_dependencies.json) >> $GITHUB_OUTPUT
          echo "filteredData (JSON): $filteredData" 
          echo "::set-output name=filteredData::$filteredData"  # Corrected output name
          echo $filteredData
      - name: Run Job
        env:
          COMPONENT_NAME: ${{ fromJSON(needs.filter-step.outputs.filteredData).name }}
          COMPONENT_VERSION: ${{ fromJSON(needs.filter-step.outputs.filteredData).version }}
        
         
  Comparison:
    runs-on: ubuntu-latest
    needs: copy_files
    continue-on-error: true
    strategy:
      matrix:
        components: ${{ fromJSON(needs.copy_files.outputs.components-info) }}
       
        filters: ${{fromJson(needs.copy_files.outputs.filtered-info).name}}
        filters1: ${{fromJson(needs.copy_files.outputs.filtered-info).version}}
      fail-fast: false
      max-parallel: 1   
    env:
      name: ${{ matrix.components.name }}
      version: ${{ matrix.components.version }}
      name1: ${{ fromJSON(matrix.filters).name }}  # Access nested data using fromJSON
      version1: ${{ fromJSON(matrix.filters1).version }}
      
    steps:
      - name: checking matrix value
        run: |
          echo "$name1"
          echo "$version1"
      
