name: Jsonsuccess Workflow
 
on:
  workflow_dispatch:
    #inputs:
      #environment:
        #description: 'Choose the env to deploy (Dev or Prod)?'
        #required: true
        #type: string
 
jobs:
 
  copy_files:
    runs-on: ubuntu-latest
    outputs:
      components-info: ${{ steps.set-matrix.outputs.backend-components }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  
        
     
      - name: Set matrix data
        id: set-matrix
        working-directory: ./job_dependencies
        run: |
          echo "backend-components=`perl -pe 's/\s+//g' job_dependencies.json`" >> $GITHUB_OUTPUT
          # Capture both stdout and stderr to a log file
          perl -pe 's/\s+//g' job_dependencies.json >> output.log 2>&1 || echo "Error occurred during perl execution" >> output.log
          
          
    
  Comparison:
    runs-on: ubuntu-latest
    needs: copy_files
    environment: 
      name: ${{ matrix.env.env }}
    continue-on-error: true
    strategy:
      matrix:
         env: ${{ fromJSON(needs.copy_files.outputs.components-info) }}
      fail-fast: false
      #max-parallel: 1
    env:
      name: ${{ matrix.env.env }}
      version: ${{ matrix.env.version }}
    steps:
      - name: checking matrix value
        run: |
          echo "$name"
          echo "$version"
      - name: Capture Errors to Log File
        if: failure()  # Only run if the job fails
        run: |
          echo "Job failed, capturing logs..." >> failure_log.txt
          cat output.log >> failure_log.txt  # Append the captured log
          
