name: Jsonsuccess Workflow
on:
  workflow_dispatch:

jobs:

  copy_files:
    runs-on: ubuntu-latest
    outputs:
      components-info: ${{ steps.set-matrix.outputs.backend-components }}
      log-output: ${{ steps.set-matrix.outputs.log-content }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set matrix data and save logs
        id: set-matrix
        working-directory: ./job_dependencies
        run: |
          # Run the command and capture its output using tee to both show in console and save to a file
          echo "Running command to parse job_dependencies.json"
          result=$(perl -pe 's/\s+//g' job_dependencies.json)
          
          # Save the result into a log file and also print it to the console
          echo "$result" | tee task.log
          
          # Set the output from the file to be available for later steps
          log_content=$(cat task.log)
          echo "backend-components=${result}" >> $GITHUB_OUTPUT   # Export the result as environment variable
          echo "log-content=${log_content}" >> $GITHUB_OUTPUT   # Set log content as output for later use

  Comparison:
    runs-on: ubuntu-latest
    needs: copy_files
    environment:
      name: ${{ matrix.env.env }}
    continue-on-error: true
    strategy:
      matrix:
        env: ${{ fromJSON(needs.copy_files.outputs.components-info) }}
      fail-fast: false
    env:
      name: ${{ matrix.env.env }}
      version: ${{ matrix.env.version }}
    steps:
      - name: checking matrix value
        run: |
          echo "Name: ${{ env.name }}"
          echo "Version: ${{ env.version }}"
      
      - name: Use log output from copy_files job
        run: |
          echo "Log from copy_files job:"
          echo "${{ needs.copy_files.outputs.log-output }}"
