name: jsonfilter
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
      Filters:
        description: 'Choose the required component'
        required: true
        type: choice
        options:
          - com1
          - com2
          - com3
jobs:
  copy_files:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      components-info: ${{ steps.set-matrix.outputs.backend-components }}
      filteredData: ${{ steps.filter-step.outputs.filteredData }}  # Corrected output name
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set matrix data
        id: set-matrix
        working-directory: ./job_dependencies
        run: |
          echo "backend-components=`perl -pe 's/\s+//g' job_dependencies.json`" >> $GITHUB_OUTPUT
          echo "$backend-components"
      - name: Filtering JSON data
        id: filter-step
        run: |
          chosencomponents="${{ github.event.inputs.Filters }}"
          
          filteredData=$(jq -c --arg chosenCom "$chosencomponents" '.[] | select(.name == $chosenCom) | .name, .version' job_dependencies/job_dependencies.json) >> $GITHUB_OUTPUT
          echo "filteredData (JSON): $filteredData" 
          filteredString=$(echo "$filteredData" | tr -d '\r\n')
          echo "::set-output name=filteredData::$filteredString"  # Corrected output name
          echo $filteredData
        
      
         
  Comparison:
    runs-on: ubuntu-latest
    needs: copy_files
    continue-on-error: true
    strategy:
      matrix:
        components: ${{ fromJSON(needs.copy_files.outputs.components-info) }}
        filtersName: ${{ split(needs.copy_files.outputs.filteredData, ',')[0] }}
        filtersVersion: ${{ split(needs.copy_files.outputs.filteredData, ',')[1] }}
      fail-fast: false
      max-parallel: 1   
    env:
      name: ${{ matrix.components.name }}
      version: ${{ matrix.components.version }}
      #name1: ${{ steps.copy_files.outputs.filtered-info.name }}  # Access nested data using fromJSON  
      #version1: ${{ steps.copy_files.outputs.filtered-info.version }}  # Access nested data using fromJSON
      
    steps:
      - name: checking matrix value
        run: |
          echo "$name1"
          echo "$version1"
      
