name: Iteration Example

on:
  workflow_dispatch:
    inputs:
      dev_value:
        description: 'Value for Dev environment'
        required: true
        type: string
      prod_value:
        description: 'Value for Prod environment'
        required: true
        type: string
      prod1_value:
        description: 'Value for Prod1 environment'
        required: true
        type: string

jobs:
  iterate-over-json-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up environment and loop through JSON keys
        run: |
          for chosenEnv in Dev Prod Prod1; do
            case $chosenEnv in
              Dev)
                chosenValue=${{ github.event.inputs.dev_value }}
                ;;
              Prod)
                chosenValue=${{ github.event.inputs.prod_value }}
                ;;
              Prod1)
                chosenValue=${{ github.event.inputs.prod1_value }}
                ;;
            esac
            echo "Processing environment: $chosenEnv"
            echo "Chosen value: $chosenValue"
            # Perform actions specific to each environment based on the chosen value
            # For example, run a command or call another action based on the chosen value
          done
