name: Iteration Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev, Prod, or Prod1)?'
        required: true
        type: string

jobs:
  iterate-over-json-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up environment and filter JSON data
        id: filter-json
        run: |
          chosenEnvironment="${{ github.event.inputs.environment }}"
          jsonData=$(cat job_dependencies/job_dependencies.json)
          filteredData=$(echo "$jsonData" | jq -r --arg chosenEnv "$chosenEnvironment" '.[$chosenEnv]')
          echo "::set-output name=filteredData::$filteredData"

      - name: Iterate over filtered JSON data
        run: |
          parsedData="${{ steps.filter-json.outputs.filteredData }}"
          for item in $(echo "$parsedData" | jq -c '.[]'); do
            echo "Processing item: $item"
          done
