name: matrixcheck Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string

jobs:

  copy_files:
    runs-on: ubuntu-latest
    outputs:
      components-info: ${{ steps.set-matrix.outputs.backend-components }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set matrix data
        id: set-matrix
        working-directory: ./job_dependencies
        run: |
          echo "backend-components=`perl -pe 's/\s+//g' job_dependencies.json`" >> $GITHUB_OUTPUT

  Comparison:
    runs-on: self-hosted
    needs: copy_files
    continue-on-error: true
    steps:
      - name: Process environments sequentially
        run: |
          $jsonData = Get-Content ./Trainbook/job_dependencies/job_dependencies.json -Raw | ConvertFrom-Json
          function ProcessEnvironment($env) {
            Write-Host "Processing environment: $env"
            $filteredData = $jsonData | Where-Object { $_.name -eq $env }
            Write-Host "Filtered data: $filteredData"
            # Perform actions specific to the environment based on the filtered data
            # For example, run a command or call another action based on the filtered data
          }
          ProcessEnvironment "Dev"
          ProcessEnvironment "Prod"
