on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string

jobs:

  copy_files:
    runs-on: ubuntu-latest
    outputs:
      components-info: ${{ steps.set-matrix.outputs.backend-components }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  
        
      - name: Set matrix data
        id: set-matrix
        working-directory: ./job_dependencies
        run: |
          echo "backend-components=`perl -pe 's/\s+//g' job_dependencies.json`" >> $GITHUB_OUTPUT

  Comparison:
    runs-on: ubuntu-latest
    needs: copy_files
    continue-on-error: true
    env:
      name: ${{ github.event.inputs.environment }}
    strategy:
      matrix:
        environment: [Dev, Prod]
    steps:
      - name: Process Environment
        run: |
          if [ "${{ matrix.environment }}" == "Dev" ]; then
            # Add the steps to process the Dev environment
            echo "Processing Dev environment"
          elif [ "${{ matrix.environment }}" == "Prod" ]; then
            # Add the steps to process the Prod environment
            echo "Processing Prod environment"
          fi
