name: matrixcheck Workflow
 
on:
  workflow_dispatch:

 
jobs:
  copy_files:
    runs-on: ubuntu-latest
    outputs:
      components-info: ${{ steps.set-matrix.outputs.backend-components }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  
        
     
      - name: Set matrix data
        id: set-matrix
        working-directory: ./job_dependencies
        run: |
          echo "backend-components=`perl -pe 's/\s+//g' job_dependencies.json`" >> $GITHUB_OUTPUT
      #- name: Check env value
        #run: echo $component
  ConditionalJob:
    runs-on: ubuntu-latest
    needs: copy_files
    steps:
      - name: Check Name and Run Workflow
        run: |
          # Read the JSON file and extract the value of the "name" field
          name=$(jq -r '.name' job_dependencies.json)
          if [ "$name" = "Dev" ]; then
            # Run the Dev workflow
            echo "Running the Dev workflow"
            # Add steps for the Dev workflow here
          else
            # Run the Prod workflow
            echo "Running the Prod workflow"
            # Add steps for the Prod workflow here
          fi
        env:
          INPUT_JSON: job_dependencies.json      
  Comparison:
    runs-on: self-hosted
    needs: copy_files
    continue-on-error: true
    strategy:
      matrix:
         components: ${{ fromJSON(needs.copy_files.outputs.components-info) }}
      fail-fast: false
    env:
      name: ${{ matrix.components.name }}
      version: ${{ matrix.components.version }}
    steps:
      - name: checking matrix value
        run: |
          echo "$name"
          echo "$version"
          
