name: pullrequest Workflow

on:
  pull_request_target:
    branches:
      - main
      - merge2
    types:
       - closed
  

    

jobs:
  build:
    #if: github.event.pull_request.merged == true
    

    runs-on: ubuntu-latest

    steps:
      
      - name: check the merge pull request
        run:  echo "Workflow executed by the main"
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: execute only if triggered by specific user
        run: echo "Workflow executed by the specifi user"
