name: NewDocker

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: maven-web-application
          path: /home/runner/work/maven-web-application/maven-web-application/target/maven-web-application.war

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image to DockerHub
        run: docker build -t mspriya92/windows-tomcat:latest .
      - name: Push Docker image to DockerHub
        run: docker push mspriya92/windows-tomcat:latest .
      
