name: Restricted Workflow

on:
  workflow_dispatch:
    

jobs:
  build:
    if: github.actor == 'username1' || github.actor == 'username2' || contains(github.actor, 'team-name/')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Add your build steps here
