name: pr-versioning

on:
  workflow_dispatch:
  #pull_request:
    #types: [labeled]
    #branches:
      #- main

jobs:
  versioning:
    #if: github.event.pull_request.merged == true
    if: github.base_ref == 'main' && github.event.pull_request.draft == false
    uses: dsidevops2024/ArtifactVersioning/.github/workflows/semantic-PRlabel-Handler.yml@main
    with:
      json_versions: ${{ vars.JSON_VERSIONS }}

  upload:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Write semver bumps
        run: |
          echo '${{ needs.versioning.outputs.updated_json }}' 

      - name: Save bumped versions to GitHub variable
        run: |
          gh variable set JSON_VERSIONS --body '${{ needs.versioning.outputs.updated_json }}' --org dsidevops2024 --visibility all
        env:
          GH_TOKEN: ${{ secrets.AVPAT_TOKEN }}
