name: PR Workflow

on:
  #workflow_dispatch:
  pull_request:
    paths:
      - './.github/Test/**'
      - './.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Add your workflow steps here
