name: PR Workflow

on:
  pull_request:
    paths:
      - '.github/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Add your workflow steps here
