name: RepoTest
on:
  workflow_dispatch:
   #inputs:
      #folder-name:
        #description: Input the foldername
        #required: true
        #default: sb
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Checking Directory
        run: |
          # Extract repository name from the GitHub repository context
          $repoOwner = "${{ github.repository_owner }}"
          Write-Host "Repository Owner: $repoOwner"
          $repoName = "${{ github.repository }}" -split '/' | select -First 1
          Write-Host "Repository Name: $repoName"
          # Get the folder name from the input or use the default
          #$folderName = "${{ inputs.folder-name }}"
          $folderName = "${{ vars.FOLDER_NAME }}"
          #$folderName = $env:FOLDER_NAME
 
          # Construct the folder path dynamically using the repository name and folder name
          #$folderpath = "$env:GITHUB_WORKSPACE\$repoName\$repoName\$folderName"
          $folderpath = "$env:GITHUB_WORKSPACE\$folderName"
          Write-Host "Folder Path: $folderpath"
        shell: powershell
