name: RepoTest
on:
  workflow_dispatch:
   inputs:
      folder-name:
        description: Input the foldername
        required: true
        default: sb
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Checking Directory
        run: |
          # Extract repository name from the GitHub repository context
          $repoName = "${{ github.repository }}" -split '/' | select -Last 1
          Write-Host "Repository Name: $repoName"
          # Get the folder name from the input or use the default
          $folderName = "${{ inputs.folder-name }}"
 
          # Construct the folder path dynamically using the repository name and folder name
          #$folderpath = "$env:GITHUB_WORKSPACE\$repoName\$repoName\$folderName"
          $folderpath = "$env:GITHUB_WORKSPACE"
          Write-Host "Folder Path: $folderpath"
        shell: pwsh
