name: Semantic Version Bump
on:
 pull_request:
 types: [closed]

 jobs:
  bump-versions:
  if: github.event.pull_request.merged == true
  runs-on: ubuntu-latest

 permissions:
  contents: read
  actions: read
  pull-request: read
  repository-projects: write

steps:
  - name: checkout
    uses: actions/checkout@v4

  - name: Setup Github CLI
    uses: cli/cli-action@v2

  - name: Get chnaged components
    id: changed
    run: |
      git fetch origin main COMPONENTS=$(git diff --name-only origin/main...HEAD | cut -d/-f1 | sort -u | uniq | jq -R -s -c 'split("\n") | map(select(length > 0))')
      echo "components=$COMPONENTS" >> $GITHUB_OUTPUT

  - name: Get SemVer bump from PR body
    id: semver
    run: |
     PR_BODY="${{ github.event.pull_request.body }}"
     if echo "$PR_BODY" | grep -q '\[x\].*Patch';then
       echo "semver=patch" >> $GITHUB_OUTPUT
     elif echo "$PR_BODY" | grep -q '\[x\].*Minor';then
        echo "semver=Minor" >> $GITHUB_OUTPUT
     elif echo "$PR_BODY" | grep -q '\[x\].*Minor';then
        echo "semver=Minor" >> $GITHUB_OUTPUT
        
     

  
  
