name: Skip workflow
on:
 workflow_dispatch:
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: run-deploy
      
        id: run-deploy # id used for referencing step
        
        uses: saulmaldonado/skip-workflow@v1
        with:
          phrase: '[deploy]'
          github-token: ${{ secrets.GITHUB_TOKEN }}


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
       
      - name: Test
        run: npm test

      - name: Deploy
        if: ${{ steps.run-deploy.outputs.skip }} # This step will only run if `[deploy]` is found
        run: npm run deploy
