name: SphereJsonUpdate

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download nsi.json artifact
        uses: actions/download-artifact@v2
        with:
          name: update-nsi-json
          path: artifacts
      - name: Print downloaded nsi.json content 
        run: cat artifacts/nsi.json
      - name: Retrieve secrets
        run: |
          DOCKER_USERNAME=$(jq -r '.DockerUsername' artifacts/nsi.json)
          DOCKER_PASSWORD=$(jq -r '.DockerPassword' artifacts/nsi.json)
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
          echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"
