name: SphereJsonUpdate

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update nsi.json with secrets
        run: |
          sed -i "s|\$DOCKER_USERNAME|${{ secrets.DOCKER_USERNAME }}|g" nsi.json
          sed -i "s|\$DOCKER_PASSWORD|${{ secrets.DOCKER_PASSWORD }}|g" nsi.json

      - name: Display updated nsi.json
        run: cat nsi.json
      - name: Print Docker Username Length
        run: echo "Docker Username Length:${#DOCKER_USERNAME}"

      - name: Print Docker Password Length (Safer Option)
        run: echo "Docker Password Length:${{ string-length(DOCKER_PASSWORD) }}" 

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add nsi.json
          git commit -m "Update nsi.json with secrets"
          git push
