name: Sphere Automation

on: 
 workflow_dispatch

jobs:
 
  
  visualize:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Getting jar from local
      run: java -jar helloworld-priya-0.0.1-SNAPSHOT.jar
      working-directory: D:\test\

    - name: Extract Jar Contents
      run: |
        # Add commands to extract jar contents here
        # For example, if the jar file is named "output.jar"
        mkdir extracted_contents
        
        unzip helloworld-priya-0.0.1-SNAPSHOT.jar -d extracted_contents
    - name: Listing the target directory
      run : ls -R 
      working-directory: D:\test\
    - name: Store as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-outputs
        path: extracted_contents
