name: Test1 workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.inputs.environment, ' ') }}
    environment: ${{ github.event_name.inputs.environment }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: set-matrix
      id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"name\":\"env\",\"config\":\"Dev\"},{\"name\":\"env\",\"config\":\"prod\"}]}"
       
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.name }}
    - run: echo ${{ matrix.config }}

  
