name: Testing workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
      Filters:
        description: 'Choose the required component'
        required: true
        type: choice
        options:
          - com1
          - com2
          - com3
jobs:
  copy_files:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      components-info: ${{ steps.set-matrix.outputs.backend-components }}
      filter-info: ${{ steps.filter-step.outputs.filteredData }}  # Update the output to include the filtered data
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Set matrix data
        id: set-matrix
        working-directory: ./job_dependencies
        run: |
          echo "backend-components=`perl -pe 's/\s+//g' job_dependencies.json`" >> $GITHUB_OUTPUT
          echo "$backend-components"
      - name: Filtering JSON data
        id: filter-step
        run: |
          chosencomponents="${{ github.event.inputs.Filters }}"
          filteredData=$(jq -r --arg chosenCom "$chosencomponents" '.[] | select(.name == $chosenCom)' job_dependencies/job_dependencies.json)
          echo "filteredData=$filteredData" >> $GITHUB_OUTPUT  # Output the filtered data to GITHUB_OUTPUT
  Comparison:
    runs-on: self-hosted
    needs: copy_files
    continue-on-error: true
    strategy:
      matrix:
        components: ${{ fromJSON(needs.copy_files.outputs.components-info) }}
        filters: ${{fromJson(needs.copy_files.outputs.filter-info)}}  # Retrieve the filtered data for use in the Comparison job
    env:
      name: ${{ matrix.components.name }}
      version: ${{ matrix.components.version }}
      name1: ${{ matrix.filters[0].name }}  # Retrieve the filtered name
      version1: ${{ matrix.filters[0].version }}  # Retrieve the filtered version
    steps:
      - name: checking matrix value
        run: |
          echo "$name1"
          echo "$version1"
