name: Matrix example

on:
  workflow_dispatch:
    

jobs:
  copy_files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1, 2, 3]
     
    steps:
      - name: Set up matrix
        run: |
          echo '{"version": "${{ matrix.version }}"}' > matrix.json
        
 
      - name: Read JSON
        run: |
          data=$(cat matrix.json)
          echo "The version is ${{fromJson(data)['version']}}"
