name: Test1 workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: set-matrix
      id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"name\":\"env\",\"config\":\"Dev\"},{\"name\":\"env\",\"config\":\"prod\"}]}"
       
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.name }}
    - run: echo ${{ matrix.config }}
   
