name: Test2
on:
  workflow_call:
    inputs:
      environment:
        type: string
    secrets:
      ADMIN_USERNAME:
        required: true

jobs:
  print-secret:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} 
    steps:
      - run: |
          echo "✅ Test2 received ADMIN_USERNAME from Trainbook dev env: ${{ secrets.ADMIN_USERNAME }}"
