name: Version-Bump-on-PR

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Bump versions for changed components
        id: bump
        uses: ./.github/actions/version-bump  # Local composite action
        with:
          base-branch: main
          json-versions: ${{ vars.JSON_VERSIONS }}

      - name: Show outputs
        run: |
          echo "Bump Type: ${{ steps.bump.outputs.bump_type }}"
          echo "Changed Components: ${{ steps.bump.outputs.components }}"
          echo "Updated JSON: ${{ steps.bump.outputs.updated_json }}"
