name: Version Bump

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main

jobs:
  bump-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Run semantic version bump
        id: version_bump
        uses: ./.github/actions/version-bump

      - name: Print new versions
        run: |
          echo "New bumped versions:"
          echo '${{ steps.version_bump.outputs.bumped_versions }}'
